name: test-then-push

on:
  pull_request:
    branches:
      - deploy
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/deploy'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Push to prod branch
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN}}
        run: |
          git checkout -B prod
          git add .
          git commit -m "Deploying to production from deploy branch" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} prod --force